language: dart

dart:
  - 2.7.0
  - dev

dart_task:
  - test: --run-skipped

jobs:
  include:
  # Only validate formatting using the dev release
  - dart: dev
    dart_task: dartfmt
  - dart: 2.6.0
    dart_task:
      dartanalyzer: --fatal-warnings .
  - dart: dev
    dart_task:
      dartanalyzer: --fatal-warnings --fatal-hints .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
