# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  preload:
    import: "package:preload/preload.dart"
    builder_factories: ["buildPreload"]
    build_extensions: {"web/index.template.html": ["web/index.html"]}
    build_to: source
    auto_apply: dependents
    required_inputs: ['.dart.js']
